name: como usar variaveis de ambiente
on:
  workflow_dispatch:
env:
  ENV_WORKFLOW: "Valor WORKFLOW"
jobs:
  teste-env:
    runs-on: ubuntu-latest
    env:
      ENV_JOB: "Valor JOB teste-env"
    steps:
      - name: Execução
        env:
          ENV_ACTION: "Valor Actiion - Execução"
        run: |
          echo "$ENV_WORKFLOW"
          echo "$ENV_JOB"
          echo "$ENV_ACTION"
      - name: Execução 2
        env:
          ENV_ACTION: "Valor Actiion - Segunda Execução"
        run: |
          echo "$ENV_WORKFLOW"
          echo "$ENV_JOB"
          echo "$ENV_ACTION"          
  teste-env-2:
    runs-on: ubuntu-latest
    env:
      ENV_JOB: "Segundo Valor JOB teste-env"
    steps:
      - name: Execução
        run: |
          echo "$ENV_WORKFLOW"
          echo "$ENV_JOB"

                
  
